//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "election")]
pub struct Model {
	#[sea_orm(primary_key, auto_increment = false)]
	pub election_id: String,
	#[sea_orm(column_type = "Text")]
	pub name: String,
	pub candidates: Vec<String>,
	pub admin_id: String,
	pub result_id: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
