//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "votes")]
pub struct Model {
	#[sea_orm(primary_key)]
	pub vote_id: i32,
	pub election_id: String,
	pub cand_order: Vec<i32>,
	pub comp_is_bigger: Vec<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
